apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: CLUSTER_NAME
  name: misc-instances
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
  machineType: m4.4xlarge
  maxSize: 1
  minSize: 1
  role: Node
  rootVolumeSize: 32
  nodeLabels:
    role: general
  subnets:
    - us-east-1a

